import 'dart:io';
import 'package:dio/dio.dart';
import 'package:permission_handler/permission_handler.dart';

class VideoDownloader {
  /// Default video download with autogenerated name
  static Future<void> downloadFromUrl(String videoUrl) async {
    String fileName = "video_${DateTime.now().millisecondsSinceEpoch}.mp4";
    await downloadFile(videoUrl, fileName);
  }

  /// Custom filename downloader
  static Future<void> downloadFile(String url, String fileName) async {
    try {
      var permission = await Permission.storage.request();
      if (!permission.isGranted) {
        print("❌ Permission denied!");
        return;
      }

      final dirPath = "/storage/emulated/0/ParrotDownloader";
      final directory = Directory(dirPath);
      if (!await directory.exists()) {
        await directory.create(recursive: true);
      }

      String fullPath = "$dirPath/$fileName";

      Dio dio = Dio();

      await dio.download(
        url,
        fullPath,
        options: Options(
          responseType: ResponseType.bytes,
          followRedirects: true,
          validateStatus: (status) => status! < 500,
        ),
        onReceiveProgress: (received, total) {
          if (total != -1) {
            print("📦 Progress: ${(received / total * 100).toStringAsFixed(0)}%");
          }
        },
      );

      print("✅ Download complete: $fullPath");
    } catch (e) {
      print("❌ Download failed: $e");
    }
  }
}